[package]
name = "ScriptsOnly"
version = "0.0.0"

[addresses]
taxed_fa_addr = "_"
thala_swap_v2_interface_addr = "_"
thala_swap_v2_router_interface_addr = "_"
hyperion_interface_addr = "_"

[dev-addresses]
taxed_fa_addr = "0x10"
thala_swap_v2_interface_addr = "0x20"
thala_swap_v2_router_interface_addr = "0x30"
hyperion_interface_addr = "0x40"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-framework.git", subdir = "aptos-framework", rev = "mainnet" }
FungibleAssetWithBuySellTax = { local = "../FungibleAssetWithBuySellTax" }
ThalaSwapV2Interface = { local = "../ThalaV2Interface" }
ThalaSwapV2RouterInterface = { local = "../ThalaV2RouterInterface" }
HyperionInterface = { local = "../HyperionInterface" }
